### ISSUE TITLE
Error: unhandled exception: cannot read from file

### ISSUE THREAD

**Issue by Yakumo-Yukari** [planety/prologue#195]
![1](https://user-images.githubusercontent.com/12076232/200251622-6bd98e8e-e0c5-412c-8f8b-dc38e5c4439f.png)

```
src\Nanako.nim(4) Nanako
.nimble\pkgs\prologue-0.6.2\prologue\core\nativesettings.nim(108) loadSettings
nim\lib\pure\json.nim(1042) parseFile
Error: unhandled exception: cannot read from file: ./config/config.debug.json [IOError]
Error: execution of an external program failed: 'Nanako\src\Nanako.exe '
```

Why does the code that follows the documentation also report an error?

**Comment by ITwrx** [comment]
well, idk if there is a bug in the docs/Prologue or not, but your error is dependent on your environment, so that is one possible reason why it would fail even though it is from the docs. 
IOW, Prologue doesn't necessarily control whether the file exists, or what permissions the file has. 

I don't have any Windows machines, and i don't remember how it handles perms all that well, but i would look at those two things if this is still a valid issue. otherwise, perhaps close the issue?
